# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY.

_commit: e6e0c0f
_src_path: git@github.com:vivienm/copier-copier
author_name: Vivien Maisonneuve
copyright_holder: Vivien Maisonneuve
copyright_year: 2024
github_account: vivienm
hosting_platform: github
license: MIT
project_description: An opinionated Copier template for Python projects.
project_name: Python project template
repo_name: copier-python-uv
