# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY.

_commit: 28737ec
_src_path: git@github.com:vivienm/copier-copier
copyright_holder: Vivien Maisonneuve
copyright_year: 2024
forge: github
github_repo: copier-python
github_user: vivienm
license: MIT
project_description: An opinionated Copier template for Python projects.
project_name: Python project template
user_name: Vivien Maisonneuve
